/*
-- Query: SELECT * FROM rms_checkplatform.checklist_info
LIMIT 0, 1000

-- Date: 2019-04-03 11:29
*/
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_PAPER','안전 서류 점검','Y','','rodem4');
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_FACILITY','작업도구/기계·기구/시설물 점검','Y','','rodem4');
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_MACHINE','장비/하역·운반 기계','Y','','rodem4');
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_WARRENT','작업허가서','Y','','rodem4');
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_WORKERACTION','작업자 불안전행동','Y','','rodem4');
INSERT INTO `CHECKLIST_INFO` (`CHECKLIST_CODE`,`CHECKLIST_NAME`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES ('CHECK_ENVIRONMENT','작업환경/상태','Y','','rodem4');
