/*
CHECK_PAPER
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전관리 조직표',1,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전관리 계획',2,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전작업 서약서',3,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'선임계',4,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전관리 자체 이행평가',5,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전보건교육계획',6,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'공정별안전점검계획',7,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'위험기계기구 및 장비 점검 계획서',8,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전관리비 사용계획',9,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'보호구지급계획',10,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전시설물 설치계획',11,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'안전작업계획',12,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'위험성평가서',13,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'근로자 건강진단 명부',14,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'보험가입',15,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'폐기물처리계획',16,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (1,'비상시긴급조치계획',17,'','Y','','rodem4');

/*
CHECK_FACILITY
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'시설물 설치 상태',1,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'전기',2,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'장비',3,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'기계·기구',4,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'인양·운반기구',5,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (2,'기타',6,'','Y','','rodem4');

/*
CHECK_MACHINE
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (3,'크레인',1,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (3,'지게차',2,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (3,'화물차',3,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (3,'차량형 장비',4,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (3,'기타',5,'','Y','','rodem4');

/*
CHECK_WARRENT
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'위험성평가',1,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'안전작업 허가서',2,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'중장비작업 허가서',3,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'화기작업 허가서',4,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'밀페공간작업 허가서',5,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'고소작업 허가서',6,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'정전작업 허가서',7,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'방사선사용작업 허가서',8,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'굴착작업 허가서',9,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (4,'기타 작업 허가서',10,NULL,'Y',NULL,'rodem4');

/*
CHECK_WORKERACTION
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'안전모',1,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'보안경',2,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'보안면',3,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'호흡 보호구',4,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'청력 보호구',5,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'안전화',6,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'안전대 착용',7,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'안전대 체결',8,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'계단 이동',9,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'전방주시',10,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'중량물 취급',11,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'무리한 작업',12,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'불안전한 행동',13,'','Y','','rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (5,'신호수 배치',14,'','Y','','rodem4');

/*
CHECK_ENVIRONMENT
*/
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'정리정돈',1,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'떨어짐 위험',2,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'넘어짐 위험',3,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'미끄럼 위험',4,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'끼임 위험',5,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'전기감전 위험',6,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'산소결핍 위험',7,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'화재/폭발 위험',8,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'가스누출 위험',9,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'안전통로 확보',10,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'작업대',11,NULL,'Y',NULL,'rodem4');
INSERT INTO `QUESTION_INFO` (`CHECKLIST_SEQ`,`QUESTION_NAME`,`DISPLAY_ORDER`,`ADD_ITEM_CODE`,`USE_YN`,`MEMO`,`MANAGER_ID`) VALUES (6,'작업계단',12,NULL,'Y',NULL,'rodem4');



