/*
-- Query: SELECT * FROM rms_checkplatform.RMS_COMM_SUB_CODE
LIMIT 0, 1000

-- Date: 2019-04-18 16:21
*/
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('EDUCATION1','건설기초안전보건교육',1,'Y','','2019-04-10 14:07:14','EDUCATION');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('EDUCATION2','안전교육(신규)',2,'Y','','2019-04-02 18:45:35','EDUCATION');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('EDUCATION3','안전교육(특별)',3,'Y','','2019-04-03 16:30:36','EDUCATION');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('EDUCATION4','안전교육(정기)',4,'Y','','2019-04-02 18:47:55','EDUCATION');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('EDUCATION5','안전교육(관리감독자)',5,'Y','','2019-04-02 18:48:46','EDUCATION');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('SENIOR1','안전보건총관책임자',1,'Y','','2019-04-02 18:43:10','SENIOR');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('SENIOR2','안전관리책임자',2,'Y','','2019-04-02 18:43:49','SENIOR');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('SENIOR3','안전관리담당자',3,'Y','','2019-04-03 16:35:15','SENIOR');
INSERT INTO `RMS_COMM_SUB_CODE` (`SUB_CODE`,`SUB_CODE_NAME`,`DISPLAY_ORDER`,`USE_YN`,`MEMO`,`REG_DATE`,`MAIN_CODE`) VALUES ('SENIOR4','관리감독자',4,'Y','','2019-04-03 16:31:12','SENIOR');
