/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.1.2.RELEASE/8.0.26.B.RELEASE
 * Generated at: 2016-01-08 09:31:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajaxgrid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1452056615642L));
    _jspx_dependants.put("jar:file:/C:/Java/pivotal-tc-server-developer-3.1.2.RELEASE/base-instance/wtpwebapps/Limitless/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"panel panel-flat\">\n");
      out.write("\t<div class=\"panel-heading\">\n");
      out.write("\t\t<h6 class=\"panel-title\">Ajax DataGrid</h6>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"panel-body\">\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<table class=\"table datatable-ajax\">\n");
      out.write("\t\t<thead>\n");
      out.write("            <tr>\n");
      out.write("            \t<th><input type=\"checkbox\" name=\"select_all\" value=\"1\" id=\"example-select-all\"></th>\n");
      out.write("                <th>Name</th>\n");
      out.write("                <th>Position</th>\n");
      out.write("                <th>Office</th>\n");
      out.write("                <th>Extn</th>\n");
      out.write("                <th>Start date</th>\n");
      out.write("                <th>Salary</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("\t</table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\tsetPageLocation(\"Ajax DataGrid\");\n");
      out.write("\t\t\n");
      out.write("\t    var dataTable = $(\".datatable-ajax\").dataTable({\n");
      out.write("\t    \tbProcessing : true,\n");
      out.write("\t    \tbServerSide : true,\n");
      out.write("\t        ajax: {\n");
      out.write("\t            url: '/getdata',\n");
      out.write("\t            type: 'POST',\n");
      out.write("\t            contentType: 'application/json',\n");
      out.write("\t    \t\tdata : function(data) { \n");
      out.write("\t    \t\t\treturn JSON.stringify(data);\n");
      out.write("\t    \t\t}\n");
      out.write("\t        },\n");
      out.write("\t        'columnDefs': [{\n");
      out.write("\t            'targets': 0,\n");
      out.write("\t            'searchable': false,\n");
      out.write("\t            'orderable': false,\n");
      out.write("\t            'className': 'dt-body-center',\n");
      out.write("\t            'render': function (data, type, full, meta){\n");
      out.write("\t                return '<input type=\"checkbox\" name=\"id[]\" value=\"' + $('<div/>').text(data).html() + '\">';\n");
      out.write("\t            }\n");
      out.write("\t         }],\n");
      out.write("\t         'order': [[1, 'asc']]\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    //Auto search disable\n");
      out.write("\t    $(\"div.dataTables_filter input\").unbind();\n");
      out.write("\t    var elelemtId = dataTable.dataTableSettings[0].sTableId;\n");
      out.write("\t    var searchInput = $(\"input[type=search][aria-controls=\"+elelemtId+\"]\");\n");
      out.write("\t    var searchButton = $(\"<button id='searchBtn' style='width: 36px;height: 36px;position: absolute;right: 0;top: 0;'></button>\");\n");
      out.write("\t    searchInput.after(searchButton);\n");
      out.write("\t    \n");
      out.write("\t\t$('#searchBtn').click(function(e){\n");
      out.write("\t\t\tdataTable.fnFilter($(\"div.dataTables_filter input\").val());\n");
      out.write("\t\t});\n");
      out.write("\t    \n");
      out.write("\t    setDataTablesInputUniform();\n");
      out.write("\t});\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
