/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.1.2.RELEASE/7.0.64.B.RELEASE
 * Generated at: 2016-02-10 12:02:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.biz.signup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import framework.util.AbleUtil;
import org.joda.time.LocalDateTime;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

public final class signupForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/layouts/biz/include.jsp", Long.valueOf(1453120580394L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

Logger logger = LoggerFactory.getLogger(this.getClass());
boolean isDevelopment = !AbleUtil.isRealProfile();
pageContext.setAttribute("isDevelopment", isDevelopment);

//page attribute
//${contextPath}	: application이 배포된 contextPath (정적리소스는 이 경로를 Prefix로 반드시 붙일 것)
//${locale}			: Response에서 사용할 locale (지역화 기준)
//${serverDateTime}	: 서버시간
pageContext.setAttribute("contextPath", request.getContextPath());
pageContext.setAttribute("locale", response.getLocale().toString());
pageContext.setAttribute("localeDashed", response.getLocale().toString().replace("_", "-"));
pageContext.setAttribute("lang", response.getLocale().getLanguage());
pageContext.setAttribute("country", response.getLocale().getCountry());
pageContext.setAttribute("serverTime", LocalDateTime.now());

if(!Boolean.TRUE.equals(request.getAttribute("pageContextJavaScriptIncluded"))) {
	request.setAttribute("pageContextJavaScriptIncluded", Boolean.TRUE);

      out.write("\t<!-- Environment - isDevelopment: ");
      out.print(isDevelopment);
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isDevelopment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow['contextPath'] = window['contextPath'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['locale'] = window['locale'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['localeDashed'] = window['localeDashed'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${localeDashed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['lang'] = window['lang'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['country'] = window['country'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${country}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['serverTime'] = window['serverTime'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</script>\r\n");
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tinput[type=file] { width: 450px; border: 1px solid #d9d9d9; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"tit\">회원 가입</h1>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layouts/biz/common/breadcrumb.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"\" id=\"signupForm\" class=\"frm-com\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t<legend class=\"blind\">회원가입</legend>\r\n");
      out.write("\t<table class=\"tbl-frm\">\r\n");
      out.write("\t\t<tbody><tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_id\">아이디</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"user_id\" class=\"input-com\" data-bind=\"value: userId\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn-com addr\" data-bind=\"click: checkUsableId\" style=\"width:100px; height:30px;\">ID중복검사</button>\r\n");
      out.write("\t\t\t\t<span class=\"txt-ps c-red error\" id=\"user_id-error\"></span>\r\n");
      out.write("\t\t\t\t<p class=\"txt-ps\">※ 아이디는 대소문자를 구분하지 않습니다.</p>\r\n");
      out.write("\t\t\t\t<p class=\"txt-ps\">※ 영문자, 숫자, _ 만 입력 가능. 최소 3자이상 입력하세요.</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"password\">패스워드</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"password\" class=\"input-com\" data-bind=\"value: password, hasFocus: passwordFocus\">\r\n");
      out.write("\t\t\t\t<span class=\"txt-ps c-red error\"></span>\r\n");
      out.write("\t\t\t\t<p class=\"txt-ps\">8자이상~16자 이내, 특수문자는 !,@,#,$,%,^,+,=,- 만 사용가능</p></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"password_chk\">패스워드 확인</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"password_chk\" class=\"input-com\" data-bind=\"value: passwordChk, hasFocus: passwordChkFocus\">\r\n");
      out.write("\t\t\t\t<span class=\"txt-ps c-red error\"></span>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_email\">이메일 주소</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com\" data-bind=\"value: emailId\"> @ \r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com\" data-bind=\"value: emailHost, hasFocus: emailHostFocus, event: { 'keyup': onEmailHostKeyEvent } \">\r\n");
      out.write("\t\t\t\t<select class=\"input-com\" data-bind=\"options: emailOptions, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: emailHostSelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tevent: { change: onEmailHostSelectChange }\">\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"user_email\" data-bind=\"value: userEmail\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_name\">이름</label></th>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"user_name\" class=\"input-com\" disabled=\"disabled\" data-bind=\"value :userRealName\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_phone\">휴대전화</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"3\" name=\"user_phone1\" data-bind=\"value: userMobilePhone1\"> - \r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"4\" name=\"user_phone2\" data-bind=\"value: userMobilePhone2\"> - \r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"4\" name=\"user_phone3\" data-bind=\"value: userMobilePhone3\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"user_phone\" data-bind=\"value: userMobilePhone\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\">생년월일</th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select id=\"user_birth_year\" class=\"input-com year\" data-bind=\"options: birthYearSelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: userBirthYYYY\">\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<label for=\"user_birth_year\">년</label>\r\n");
      out.write("\t\t\t\t<select id=\"user_birth_month\" class=\"input-com month\" data-bind=\"options: birthMonthSelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: userBirthMM\">\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<label for=\"user_birth_month\">월</label>\r\n");
      out.write("\t\t\t\t<select id=\"user_birth_day\" class=\"input-com day\" data-bind=\"options: birthDaySelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: userBirthDD\">\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<label for=\"user_birth_day\">일</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_sex\">성별</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"user_sex\" id=\"male\" data-bind=\"checked: userSex\" value=\"M\">\r\n");
      out.write("\t\t\t\t<label for=\"male\">남자</label>\r\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"user_sex\" id=\"female\" data-bind=\"checked: userSex\" value=\"F\">\r\n");
      out.write("\t\t\t\t<label for=\"female\">여자</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"user_address\">자택주소</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com addr-num\" name=\"user_address1\" disabled=\"disabled\" data-bind=\"value: userPostNumber\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn-com addr\" data-bind=\"click: userAddressSelectPopup\">우편번호찾기</a><br/>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com addr mg\" name=\"user_address2\" disabled=\"disabled\" data-bind=\"value: userAddress1\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com mg\" name=\"user_address3\" data-bind=\"value: userAddress2 , hasFocus: userAddress2Focus\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"user_address\" data-bind=\"value: userFullAddress\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"company\">회사명</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"company\" class=\"input-com\" data-bind=\"value: company\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"company_phone\">회사전화</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"4\" name=\"company_phone1\" data-bind=\"value: companyPhone1\"> - \r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"4\" name=\"company_phone2\" data-bind=\"value: companyPhone2\"> - \r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com phone positive-integer\" maxlength=\"4\" name=\"company_phone3\" data-bind=\"value: companyPhone3\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"company_phone\" data-bind=\"value: companyPhone\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"company_address\">회사주소</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com addr-num\" name=\"company_address1\" disabled=\"disabled\" data-bind=\"value: companyPostNumber\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"btn-com addr\" data-bind=\"click: companyAddressSelectPopup\">우편번호찾기</a><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com addr mg\" name=\"company_address2\" disabled=\"disabled\" data-bind=\"value: companyAddress1\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input-com mg\" name=\"company_address3\" data-bind=\"value: companyAddress2, hasFocus: companyAddress2Focus\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"company_address\" data-bind=\"value: companyFullAddress\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"uploadedFile\">재직증명서 등록</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"margin:0 0 10px 0;\">\r\n");
      out.write("\t\t\t\t\t<span class=\"txt-guide\">재직증명서 파일 첨부</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"txt-ps c-red\">* 10MB 이내의 이미지파일(jpg, gif, png, bmp,pdf) 만 업로드 가능합니다.</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"file\" id=\"uploadedFile\" name=\"uploadedFile\" class=\"input-com\" data-bind=\"event: {change: uploadedFileChanged}\">\r\n");
      out.write("\t\t\t\t<span class=\"txt-ex\">ex) 재직증명서.pdf</span>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th scope=\"row\"><label for=\"rd-work\">근로자 형태</label></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<ul class=\"radio-list\" data-bind=\"foreach: $root.USER_WORK_TYPE_CODE_MAP\">\r\n");
      out.write("\t\t\t\t\t<li><input type=\"radio\" name=\"rd-work\" data-bind=\"checked: $root.userWorkType, checkedValue: $data.value, attr: { 'id': 'rd'+ $index() }\">\r\n");
      out.write("\t\t\t\t\t\t<label data-bind=\"text: $data.name, attr: { 'for': 'rd'+ $index() } \"></label>\r\n");
      out.write("\t\t\t\t\t\t<!-- ko if: $data.value == \"U\" -->\r\n");
      out.write("\t\t\t\t\t\t<span class=\"due-date\" data-bind=\"with: $root, visible: $root.isUnemployDateVisible\">\r\n");
      out.write("\t\t\t\t\t\t\t실직일 : \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"user_end_year\" class=\"input-com year\" data-bind=\"options: unemployYearSelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: unemployYYYY\">\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"user_end_year\">년</label>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"user_end_month\" class=\"input-com month\" data-bind=\"options: unemployMonthSelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: unemployMM\">\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"user_end_month\">월</label>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"user_end_day\" class=\"input-com day\" data-bind=\"options: unemployDaySelect, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsText: function(item) { return item.name }, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\toptionsValue: function(item) { return item.value },\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue: unemployDD\">\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"user_end_day\">일</label>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t<!-- /ko -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</tbody></table><!-- //.tbl-frm -->\r\n");
      out.write("\t<div class=\"btn-wrap\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn-bcom\" data-bind=\"click: insertUser\">회원가입하기</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn-bcom btn-gray\" data-bind=\"click: cancel\">취소</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</form><!-- //.frm-com -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar pageURL = {\r\n");
      out.write("\t\tapi_checkUsableId: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/api/signup/checkUsableId.json\",\r\n");
      out.write("\t\tapi_insertUser: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/api/signup/insertuser.json\",\r\n");
      out.write("\t\tapi_checkKMCOwnerCert: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/api/signup/checkKMCOwnerCert.json\"\r\n");
      out.write("\t};\r\n");
      out.write("\tvar certParam = {\r\n");
      out.write("\t\tauthType: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\tcertNum: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${certNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\trec_cert: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rec_cert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\treqNum: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reqNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\tretInfo: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${retInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\tcbParam: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cbParam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t};\r\n");
      out.write("\tvar USER_WORK_TYPE_CODE_MAP = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USER_WORK_TYPE_CODE_MAP}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/lib/jquery.iframe-transport.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/app/biz/signup/signupForm.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/layouts/biz/include.jsp(39,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty meJSON}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\twindow['me'] = window['me'] || ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meJSON}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(";\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
