/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.1.2.RELEASE/7.0.64.B.RELEASE
 * Generated at: 2016-02-10 10:42:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.biz.festival.music;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import framework.util.AbleUtil;
import org.joda.time.LocalDateTime;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

public final class applyStep3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/layouts/biz/include.jsp", Long.valueOf(1453120580394L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

Logger logger = LoggerFactory.getLogger(this.getClass());
boolean isDevelopment = !AbleUtil.isRealProfile();
pageContext.setAttribute("isDevelopment", isDevelopment);

//page attribute
//${contextPath}	: application이 배포된 contextPath (정적리소스는 이 경로를 Prefix로 반드시 붙일 것)
//${locale}			: Response에서 사용할 locale (지역화 기준)
//${serverDateTime}	: 서버시간
pageContext.setAttribute("contextPath", request.getContextPath());
pageContext.setAttribute("locale", response.getLocale().toString());
pageContext.setAttribute("localeDashed", response.getLocale().toString().replace("_", "-"));
pageContext.setAttribute("lang", response.getLocale().getLanguage());
pageContext.setAttribute("country", response.getLocale().getCountry());
pageContext.setAttribute("serverTime", LocalDateTime.now());

if(!Boolean.TRUE.equals(request.getAttribute("pageContextJavaScriptIncluded"))) {
	request.setAttribute("pageContextJavaScriptIncluded", Boolean.TRUE);

      out.write("\t<!-- Environment - isDevelopment: ");
      out.print(isDevelopment);
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isDevelopment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow['contextPath'] = window['contextPath'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['locale'] = window['locale'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['localeDashed'] = window['localeDashed'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${localeDashed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['lang'] = window['lang'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lang}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['country'] = window['country'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${country}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\twindow['serverTime'] = window['serverTime'] || \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</script>\r\n");
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"tit\">참가신청</h1>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/layouts/biz/common/breadcrumb.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"tit-step\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/img-step03-music.jpg\" alt=\"step3 접수방법\"></h2>\r\n");
      out.write("<form action=\"\" class=\"frm-com step\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t<legend class=\"blind\">접수방법 선택</legend>\r\n");
      out.write("\t<div class=\"req-method-wrap\">\r\n");
      out.write("\t\t<h3 class=\"tit\">접수방법 선택</h3>\r\n");
      out.write("\t\t<div class=\"method-box\">\r\n");
      out.write("\t\t\t<span>근로자 음악제는 3가지 방법으로 접수 가능합니다.</span>\r\n");
      out.write("\t\t\t<ol class=\"tit-info\">\r\n");
      out.write("\t\t\t\t<li class=\"eq0\"><strong class=\"tit\">ARS 지원</strong> : 1670-0075로 전화 접수!</li>\r\n");
      out.write("\t\t\t\t<li class=\"eq1\"><strong class=\"tit\">UCC 지원</strong> : 내 노래 영상을 찍고 YouTube에 동영상을 업로드!</li>\r\n");
      out.write("\t\t\t\t<li class=\"eq2\"><strong class=\"tit\">현장 오디션</strong> : 지역을 선택한 후, 현장에서 직접 예심을!</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<ul class=\"method-mn ofh\">\r\n");
      out.write("\t\t\t\t<li><input type=\"radio\" name=\"method\" id=\"meth01\" value=\"ARS\" data-bind=\"checked: applyType, enable: inDuration\"><label for=\"meth01\">ARS 지원</label></li>\r\n");
      out.write("\t\t\t\t<li><input type=\"radio\" name=\"method\" id=\"meth02\" value=\"UCC\" data-bind=\"checked: applyType, enable: inDuration\"><label for=\"meth02\">UCC 지원</label></li>\r\n");
      out.write("\t\t\t\t<li><input type=\"radio\" name=\"method\" id=\"meth03\" value=\"AUDITION\" data-bind=\"checked: applyType, enable: inDuration\"><label for=\"meth03\">현장 오디션</label></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"req-method ofh\" data-bind=\"css: {on: applyType()=='ARS'}\">\r\n");
      out.write("\t\t\t\t<div class=\"fl\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/method-ars.png\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"tit\">ARS 접수 방법</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt-guide\">1670-0075로 전화하시면 시간과 장소에 관계없이<br>전화로 오디션에 참여할 수 있습니다.</p>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt-ps\">※ ARS 오디션은 휴대폰 국내통화료 외에 별도의 정보 이용료는 부과되지 않습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- //.req-method -->\r\n");
      out.write("\t\t\t<div class=\"req-method ofh\" data-bind=\"css: {on: applyType()=='UCC'}\">\r\n");
      out.write("\t\t\t\t<div class=\"fl\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/method-ucc.png\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"fl meth-ucc\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"tit\">UCC 접수 방법</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt-guide\">휴대폰 혹은 기타 기기를 통해 YouTube 홈페이지에 동영상을 등록해주세요.</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.youtube.com/\" class=\"btn-com btn-yt-home\" target=\"_new\">YouTube 홈페이지 바로가기</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://support.google.com/youtube/topic/16547?hl=ko&ref_topic=4355169\" class=\"btn-com btn-yt-upload\" target=\"_new\">YouTube 업로드 알아보기</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"yt-info\">유튜브 동영상 URL을 적어주세요.<br>(유튜브 동영상 [공유] 클릭시 나오는 URL을 모두 정확하게 기입해주세요)</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"uccUrl\" class=\"\" title=\"유튜브 동영상 URL\" data-bind=\"value: uccUrl, enable: inDuration\"  maxlength=\"256\">\r\n");
      out.write("\t\t\t\t\t<p class=\"yt-info\">유튜브 동영상 제목을 적어주세요.</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"uccTitle\" class=\"\" title=\"유튜브 동영상 제목\" data-bind=\"value: uccTitle, enable: inDuration\"  maxlength=\"50\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- //.req-method -->\r\n");
      out.write("\t\t\t<div class=\"req-method ofh\" data-bind=\"css: {on: applyType()=='AUDITION'}\">\r\n");
      out.write("\t\t\t\t<div class=\"fl\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/method-audition.png\" alt=\"\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"fl\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"tit\">현장 오디션 접수 방법</h4>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt-guide\">현장에서 오디션을 받고 싶으신 분은 아래 지역 중 원하시는 지역을 선택해 주세요.<br>현장 오디션 접수자분께는 별도 연락을 통해 알려드립니다.</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"method-radio-list ofh\">\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area01\" value=\"서울\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area01\">서울</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area02\" value=\"수원\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area02\">수원</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area03\" value=\"대전\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area03\">대전</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area04\" value=\"창원\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area04\">창원</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area05\" value=\"대구\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area05\">대구</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area06\" value=\"전주\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area06\">전주</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area07\" value=\"광주\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area07\">광주</label></li>\r\n");
      out.write("\t\t\t\t\t\t<li><input type=\"radio\" name=\"area\" id=\"area08\" value=\"안산\" data-bind=\"checked: auditionLocation, enable: inDuration\"><label for=\"area08\">안산</label></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<p class=\"txt-ps c-red\">*안산 지역은 외국인만 신청 가능합니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- //.req-method -->\r\n");
      out.write("\t\t</div><!-- //.method-box -->\r\n");
      out.write("\t</div><!-- //.req-method-wrap -->\r\n");
      out.write("\t<p class=\"txt-request tac\">위와 같이 제37회 근로자문화예술제 참가를 신청합니다.</p>\r\n");
      out.write("\t<p class=\"user-request\"><span data-bind=\"text: moment().format('YYYY년 MM월 DD일')\"></span> 신청자 <span class=\"sign\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${me.userRealName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></p>\r\n");
      out.write("\t<div class=\"btn-wrap\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn-bcom btn-gray\" data-bind=\"click: goPrev\">이전</button>\r\n");
      out.write("\t\t<!-- ko if: inDuration -->\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn-bcom btn-gray btn-save\" data-bind=\"click: saveTemp\">임시저장</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn-bcom pos\" data-bind=\"click: saveFinal\">최종제출</button>\r\n");
      out.write("\t\t<!-- /ko -->\r\n");
      out.write("\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/festival\" class=\"btn-bcom pos\" data-bind=\"visible: !inDuration()\">처음으로</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar pageParam = {\r\n");
      out.write("\t\tfestival: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${festival}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(",\r\n");
      out.write("\t\tcategory: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar apply = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apply}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" || {};\r\n");
      out.write("\tvar applyMusic = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${applyMusic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" || {};\r\n");
      out.write("\tapply = _.extend(apply, applyMusic);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/app/biz/festival/music/applyStep3.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/layouts/biz/include.jsp(39,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty meJSON}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\twindow['me'] = window['me'] || ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${meJSON}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write(";\r\n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
